config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'jobs#index'

  resources :jobs, only: [:index, :show, :new, :create]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authorize
    unless current_user.try(:admin)
      flash[:notice] = 'You must be an admin to add job listings.'
      redirect_to jobs_path
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_action :authorize, only: [:new, :create]

  def index
    jobs = call_jobs_api
    jobs.sort_by! { |job| job["posted"] }.reverse!

    if params[:keywords].try(:present?)
      jobs.select! { |job| job["keywords"].include?(params[:keywords].downcase) }
    end

    if params[:location].try(:present?)
      collected = []
      collected << jobs.select { |job| job["city"].include?(params[:location].titleize) }
      collected << jobs.select { |job| job["state"].include?(params[:location].upcase) }
      jobs = collected.flatten
    end

    @jobs_count = jobs.count
    @jobs = jobs.paginate(page: params[:page], per_page: 10)
  end

  def show
    jobs = call_jobs_api
    @job = jobs[params[:id].to_i - 1]

    post_events_api(@job)
  end

  def new
  end

  def create
    response = post_jobs_api(params[:job])

    if response.code == "200"
      redirect_to jobs_path
    else
      render 'new'
    end
  end

  private

  def call_jobs_api
    uri = URI.parse("http://localhost:4000/jobs")
    response = Net::HTTP.get_response(uri)
    JSON.parse(response.body)
  end

  def post_events_api(job)
    uri = URI.parse("http://localhost:4000/events")
    Net::HTTP.post_form(uri,
      {
        "job_id" => job["id"].to_i,
        "clicked" => Time.now.to_i,
        "user_id" => current_user.try(:id)
      }
    )
  end

  def post_jobs_api(job_params)
    uri = URI.parse("http://localhost:4000/jobs")
    Net::HTTP.post_form(uri,
      {
        "posted" => Time.now.to_i,
        "company" => job_params[:company],
        "poster" => current_user.email,
        "city" => job_params[:city],
        "state" => job_params[:state],
        "title" => job_params[:title],
        "body" => job_params[:body],
        "keywords" => job_params[:keywords]
      }
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_job_result.html.erb
<div class="job">
  <%= link_to job["title"], job_path(job["id"]) %></br>
  <span class="job-subtitle">
    <%= "#{job["company"]} - #{job["city"]}, #{job["state"]}" %></br>
  </span>
  <span class="job-posted">
    <%= "#{Time.at(job["posted"]).strftime("%b %e, %Y")}" %>
  </span>
  <span class="job-description">
    <%=  "- #{job["body"]}" %></br>
  </span>
</div>

app/views/jobs/index.erb
<header>
  <%= link_to root_path do %>
    <h2><span>Job</span>Searcher</h2>
  <% end %>
  <%= form_tag(jobs_path, method: 'GET', id: 'search-form') do %>
    <%= text_field_tag :keywords, params[:keywords], placeholder: 'Keywords' %>
    <%= text_field_tag :location, params[:location], placeholder: 'Location' %>
    <%= submit_tag "Search" %>
  <% end %>
  <div id="userActions">
    <% if current_user %>
      <%= link_to 'Post Job', new_job_path %>
    <% else %>
      <%= link_to 'Log In', new_user_session_path %>
    <% end %>
  </div>
</header>

<div id="welcome">
  <h1>Welcome to JobSearcher!</h1>
  <strong><%= pluralize(@jobs_count, 'job') %> found</strong>
</div>
<div id="results">
  <% @jobs.each do |job| %>
    <%= render "job_result", job: job %>
    </br>
  <% end %>
</div>
<div class="digg_pagination">
  <%= will_paginate @jobs, previous_label: "«", next_label: "»" %>
</div>

app/views/jobs/new.erb
<div id="newPost">
  <%= form_for :job, url: jobs_path do |f| %>
    <%= f.label :company %><br />
    <%= f.text_field :company %><br />
    <%= f.label :city %><br />
    <%= f.text_field :city %><br />
    <%= f.label :state %><br />
    <%= f.text_field :state %><br />
    <%= f.label :title %><br />
    <%= f.text_field :title %><br />
    <%= f.label :body %><br />
    <%= f.text_field :body %><br />
    <%= f.label :keywords %><br />
    <%= f.text_field :keywords %><br />
    <%= f.submit %>
  <% end %>
</div>

app/views/jobs/show.erb
<%= render "job_result", job: @job %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobSearchExercise</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>